apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-1
spec:
  containers:
    - name: demo-container-1
      image: alpine:latest
      command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-2
spec:
  containers:
    - name: demo-container-2
      image: alpine:latest
      command: ["sleep", "3600"]

