apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: user1-role
    namespace: user1
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["pods", "services"]
  verbs: ["create", "delete", "get", "list", "update", "watch"]
